---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: custom-error-page
    namespace: ingress
    files:
      - response.body=error-minify.html # to get this: run HTML through CyberChef HTML minify, then replace all single % with double to escape Envoy local_reply 'commands', then optionally replace error code in HTML with `%RESPONSE_CODE%`
generatorOptions:
  disableNameSuffixHash: true
