---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  # - secrets-restic.yaml
  - externalsecret-r2.yaml
  # - externalsecret-rgw.yaml
  - rdst.yaml
  - rsrc-r2.yaml
  # - rsrc-rgw.yaml
