---
# yaml-language-server: $schema=https://flux.jank.ing/ocirepository-source-v1.json?test
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trust-manager
  namespace: trust-manager
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://quay.io/jetstack/charts/trust-manager
  ref:
    tag: v0.21.1@sha256:ae5d010ebd73c3c6d687673759aa9e2d7ee200125b393e1563bfb2b5b478aa39
