---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trilium-app
  namespace: flux-system
  labels: &l
    app.kubernetes.io/name: "trilium"
spec:
  targetNamespace: "trilium"
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/trilium/app
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: trilium-pvc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trilium-pvc
  namespace: flux-system
  labels: &l
    app.kubernetes.io/name: trilium
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: trilium
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: "trilium-data"
      SIZE: "10Gi"
      SC: &sc "file"
      SNAP: *sc
      ACCESSMODE: "ReadWriteMany"
      SNAP_ACCESSMODE: "ReadOnlyMany"
      VS_APP_CURRENT_VERSION: "ghcr.io/triliumnext/trilium:v0.101.3@sha256:f9c978d08f24af19e58c7e3230218a5a6a0ab889ac261e25edb847ebd3762ff4"
      RUID: &uid "1001"
      RGID: *uid
      RFSG: *uid
