---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: continuwuity-app
  namespace: &ns continuwuity
  labels: &l
    app.kubernetes.io/name: "continuwuity"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/continuwuity/app
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: continuwuity-data
    - name: continuwuity-mass
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &pvc continuwuity-data
  namespace: &ns continuwuity
  labels: &l
    app.kubernetes.io/name: continuwuity
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: *pvc
      SIZE: "5Gi"
      SC: &sc "block"
      SNAP: *sc
      ACCESSMODE: &am "ReadWriteOnce"
      SNAP_ACCESSMODE: *am
      VS_APP_CURRENT_VERSION: "forgejo.ellis.link/continuwuation/continuwuity:v0.5.5-maxperf@sha256:467801ef68a22772147ac6088976d5284ec9f3a2182f004a8432ceb3af7a2319"
      RUID: &uid "65534"
      RGID: *uid
      RFSG: *uid
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "continuwuity-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.conditions.filter(s, s.status == "False").all(s, s.reason == "WaitingForManual" || s.reason == "WaitingForSchedule") && status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed" # TODO: add failed conditions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &pvc continuwuity-mass
  namespace: &ns continuwuity
  labels: &l
    app.kubernetes.io/name: continuwuity
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: *pvc
      SIZE: "50Gi"
      SC: &sc "file-ec-2-1"
      SNAP: "file"
      ACCESSMODE: "ReadWriteMany"
      SNAP_ACCESSMODE: "ReadOnlyMany"
      VS_APP_CURRENT_VERSION: "forgejo.ellis.link/continuwuation/continuwuity:v0.5.5-maxperf@sha256:467801ef68a22772147ac6088976d5284ec9f3a2182f004a8432ceb3af7a2319"
      RUID: &uid "65534"
      RGID: *uid
      RFSG: *uid
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "continuwuity-mass-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.conditions.filter(s, s.status == "False").all(s, s.reason == "WaitingForManual" || s.reason == "WaitingForSchedule") && status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed" # TODO: add failed conditions
