---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${CLUSTER_NAME:=biohazard}-vars"
  namespace: home-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: ".${CLUSTER_NAME}-vars"
    - extract:
        key: "authentik vars - ${CLUSTER_NAME}"
    - extract:
        key: "Home Assistant - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        # Core cluster-wide vars
        CLUSTER_NAME: "${CLUSTER_NAME:=biohazard}"
        CONFIG_TZ: '{{ .CONFIG_TZ }}'
        # App specific
        APP_DNS_HOME_ASSISTANT: '{{ .APP_DNS_HOME_ASSISTANT }}'
        APP_IP_HOME_ASSISTANT: '{{ .APP_IP_HOME_ASSISTANT }}'
        # Multus
        APP_IP_HOME_ASSISTANT_IOT: '{{ .APP_IP_HOME_ASSISTANT_IOT }}'
        APP_MAC_HOME_ASSISTANT_IOT: '{{ .APP_MAC_HOME_ASSISTANT_IOT }}'
        IP_ROUTER_VLAN_IOT: '{{ .IP_ROUTER_VLAN_IOT }}'
        # authentik hostAliases
        APP_DNS_AUTHENTIK: '{{ .APP_DNS_AUTHENTIK }}'
        APP_IP_AUTHENTIK: '{{ .APP_IP_AUTHENTIK }}'
        # Other cluster-wide vars
        DNS_CF: '{{ .DNS_CF }}'
