---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-nas
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: &ps baseline
    pod-security.kubernetes.io/audit: *ps
    pod-security.kubernetes.io/warn: *ps
