---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: &ps restricted
    pod-security.kubernetes.io/audit: *ps
    pod-security.kubernetes.io/warn: *ps
