---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${CLUSTER_NAME:=biohazard}-vars"
  namespace: authentik
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: ".${CLUSTER_NAME}-vars"
    - extract:
        key: "authentik - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        # Core cluster-wide vars
        CLUSTER_NAME: "${CLUSTER_NAME:=biohazard}"
        CONFIG_TZ: '{{ .CONFIG_TZ }}'
        # App specific
        APP_DNS_AUTHENTIK: '{{ .APP_DNS_AUTHENTIK }}'
        APP_IP_AUTHENTIK: '{{ .APP_IP_AUTHENTIK }}'
        APP_DNS_AUTHENTIK_LDAP: '{{ .APP_DNS_AUTHENTIK_LDAP }}'
        APP_IP_AUTHENTIK_LDAP: '{{ .APP_IP_AUTHENTIK_LDAP }}'
        APP_DNS_AUTHENTIK_RADIUS: '{{ .APP_DNS_AUTHENTIK_RADIUS }}'
        APP_IP_AUTHENTIK_RADIUS: '{{ .APP_IP_AUTHENTIK_RADIUS }}'
        # Other cluster-wide vars
        IP_POD_CIDR_V4: '{{ .IP_POD_CIDR_V4 }}'
        IP_ROUTER_VLAN_K8S: '{{ .IP_ROUTER_VLAN_K8S }}'
        DNS_CF: '{{ .DNS_CF }}'
        DNS_MAIN: '{{ .DNS_MAIN }}'
