---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor
handler: runsc-kvm
scheduling:
  nodeSelector:
    feature.node.kubernetes.io/baremetal: "true"
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor-non-vm
handler: runsc
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
handler: kata
overhead:
  podFixed:
    memory: "130Mi"
    cpu: "10m"
scheduling:
  nodeSelector:
    feature.node.kubernetes.io/baremetal: "true"
