---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-app
  namespace: &ns ingress
  labels: &l
    app.kubernetes.io/name: "envoy-gateway"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/ingress/envoy-gateway/app
  components:
    - ../../../flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-gateways
  namespace: &ns ingress
  labels: &l
    app.kubernetes.io/name: envoy-gateway
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/ingress/envoy-gateway/gateways
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: envoy-gateway-app
