---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-internal
  namespace: ingress
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: continuwuity
  connection:
    bufferLimit: 8Mi
  http2:
    initialStreamWindowSize: 2Mi
    initialConnectionWindowSize: 32Mi
    onInvalidMessage: TerminateStream
  tcpKeepalive: {}
  timeout:
    http:
      requestReceivedTimeout: 120s
