---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app continuwuity
  namespace: *app
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: *app
  values:
    controllers:
      app:
        type: deployment
        replicas: 1
        pod:
          labels: # netpols
            ingress.home.arpa/envoy-internal: allow
            ingress.home.arpa/envoy-external: allow
            # authentik.home.arpa/oidc: allow
            authentik.home.arpa/ldap: allow
            # prom.home.arpa/kps: allow
            # egress.home.arpa/internet: allow
            egress.home.arpa/mullvad: allow
          annotations:
            k8s.v1.cni.cncf.io/networks: | # VPN
              [{
                "name":"vpn-vlan",
                "namespace": "multus",
                "ips": ["${APP_IP_CONTINUWUITY_VPN}"],
                "mac": "${APP_MAC_CONTINUWUITY_VPN}"
              }]
        containers:
          app:
            image: &img
              repository: forgejo.ellis.link/continuwuation/continuwuity
              tag: v0.5.5-maxperf@sha256:467801ef68a22772147ac6088976d5284ec9f3a2182f004a8432ceb3af7a2319
            env: &env
              # core settings (FOR YOINKERS)
              TZ: "${CONFIG_TZ}"
              CONDUWUIT_SERVER_NAME: jjgadgets.tech
              CONDUWUIT_ADDRESS:
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              CONDUWUIT_PORT: &http 8080
              CONDUWUIT_DATABASE_PATH: &data /data
              CONDUWUIT_DATABASE_BACKUP_PATH: &backup /backups
              CONDUWUIT_DATABASE_BACKUPS_TO_KEEP: 2
              CONDUWUIT_NEW_USER_DISPLAYNAME_SUFFIX: ""
              CONDUWUIT_WELL_KNOWN__CLIENT: "https://${APP_DNS_CONTINUWUITY}"
              CONDUWUIT_WELL_KNOWN__SERVER: "${APP_DNS_CONTINUWUITY_SERVER}:443"
              CONDUWUIT_ALLOW_ENCRYPTION: true
              CONDUWUIT_ALLOW_FEDERATION: true
              CONDUWUIT_ALLOW_REGISTRATION: true
              CONDUWUIT_REGISTRATION_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: continuwuity-secrets
                    key: CONDUWUIT_REGISTRATION_TOKEN
              CONDUWUIT_EMERGENCY_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: continuwuity-secrets
                    key: CONDUWUIT_EMERGENCY_PASSWORD
              # HIGHLY RECOMMENDED but OPTIONAL
              # anti Matrix Synapse, we're only interested in Matrix the protocol amongst our community
              # NOTE: this will block joining *spaces* from homeservers that have matrix.org users federated
              # BUT you CAN join *ROOMS* from these servers, and get the parts of the room that are NOT from matrix.org
              CONDUWUIT_QUERY_TRUSTED_KEY_SERVERS_FIRST: false # NOTE: this is because continuwuity only supports Synapse as trusted key servers
              CONDUWUIT_QUERY_TRUSTED_KEY_SERVERS_FIRST_ON_JOIN: false
              CONDUWUIT_FORBIDDEN_REMOTE_SERVER_NAMES: |
                ["matrix.org"]
              CONDUWUIT_FORBIDDEN_REMOTE_ROOM_DIRECTORY_SERVER_NAMES: |
                ["matrix.org"]
              CONDUWUIT_URL_PREVIEW_DOMAIN_EXPLICIT_DENYLIST: |
                ["matrix.org"]
              # ======================================================================
              # BELOW IS NOT REQUIRED FOR ANYBODY YOINKING MY CONFIG
              # these are settings specific to my environment and risk appetite
              # you may change these however you like according to your preferences
              # refer to upstream docs before including any of these
              # ======================================================================
              # NOT REQUIRED FOR YOINKERS! but nice to have, tinfoil & personal preferences
              CONDUWUIT_ALLOW_OUTGOING_READ_RECEIPTS: false
              CONDUWUIT_ALLOW_ANNOUNCEMENTS_CHECK: false
              CONDUWUIT_SUSPEND_ON_REGISTER: false
              # CONDUWUIT_FORGET_FORCED_UPON_LEAVE: true
              CONDUWUIT_REQUIRE_AUTH_FOR_PROFILE_REQUESTS: true
              CONDUWUIT_ALLOW_PUBLIC_ROOM_DIRECTORY_WITHOUT_AUTH: false
              CONDUWUIT_ALLOW_PUBLIC_ROOM_DIRECTORY_OVER_FEDERATION: false
              CONDUWUIT_LOCKDOWN_PUBLIC_ROOM_DIRECTORY: true
              CONDUWUIT_ALLOW_LEGACY_MEDIA: false # unauthenticated
              CONDUWUIT_DEFAULT_ROOM_VERSION: "12" # more secure, room/space creator has highest power
              CONDUWUIT_CONFIG_RELOAD_SIGNAL: true # idk if we can have Reloader hit this endpoint instead or something?
              # NOT REQUIRED FOR YOINKERS! external auth (wen eta OIDC/SAML)
              CONDUWUIT_LDAP__ENABLE: true
              CONDUWUIT_LDAP__LDAP_ONLY: true
              CONDUWUIT_LDAP__URI: "ldaps://${APP_DNS_AUTHENTIK_LDAP}:636"
              CONDUWUIT_LDAP__BIND_DN: CN=continuwuity-ldap,OU=service-accounts,OU=goauthentik.io,DC=ldap,DC=goauthentik,DC=io
              CONDUWUIT_LDAP__BIND_PASSWORD_FILE: &ldap-secret /secrets/ldap-bind-password
              CONDUWUIT_LDAP__BASE_DN: DC=ldap,DC=goauthentik,DC=io
              CONDUWUIT_LDAP__FILTER: "(memberOf=CN=Role-Continuwuity-User,OU=groups,DC=ldap,DC=goauthentik,DC=io)"
              CONDUWUIT_LDAP__ADMIN_FILTER: "(memberOf=CN=Role-Continuwuity-Admin,OU=groups,DC=ldap,DC=goauthentik,DC=io)"
              CONDUWUIT_LDAP__UID_ATTRIBUTE: "continuwuityUsername" # authentik users can't change usernames by themselves, UID usernames is weird
              CONDUWUIT_LDAP__NAME_ATTRIBUTE: "displayName" # authentik users can't change usernames by themselves, UID usernames is weird
              # =============================
              # END OF DO NOT YOINK SECTION
              # =============================
            envFrom: &envFrom
              - secretRef:
                  name: continuwuity-secrets
            securityContext: &sc
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: "10m"
              limits:
                cpu: "3"
                memory: "512Mi"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        controller: app
        ports:
          http:
            port: 80
            targetPort: *http
            protocol: HTTP
            appProtocol: http
    route:
      app: # to use an account domain that differs from your Matrix server domain, add a 301 from https://domain.tld/.well-known/matrix/* to https://continuwuity.domain.tld/.well-known/matrix/* and preserve path suffix (the wildcard part), e.g. https://github.com/JJGadgets/jjgadgets.tech/blob/dcbaa6d9e884953fe8e97505cce2b8bfce53a312/static/_redirects#L2
        annotations:
          external-dns.alpha.kubernetes.io/target: "${DNS_CF:=cf}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hostnames: ["${APP_DNS_CONTINUWUITY:=continuwuity}", "${APP_DNS_CONTINUWUITY_SERVER:=continuwuity}"] # no harm separating client facing and server-to-server hostnames, maybe allows for some flexibility to move things around in the future? idk, same hostnames also seems fine, monoxane uses single
        parentRefs: # k8s-gateway DNS only serves internal gateway class
          - name: envoy-internal
            namespace: ingress
            sectionName: internal
          - name: envoy-external
            namespace: ingress
            sectionName: public
    persistence:
      data: # Ceph 3 replicas, a normal pool size
        existingClaim: continuwuity-data
        advancedMounts:
          app:
            app:
              - subPath: data
                path: *data
      mass: # Ceph EC 2-1 for bigger and less critical data
        # you can either use your NAS for this or just have it all in the PVC
        # I have it this way because my Ceph cluster has >60% space used lol
        existingClaim: continuwuity-mass
        advancedMounts:
          app:
            app:
              - subPath: media
                path: /data/media
              - subPath: backups
                path: *backup
      secrets:
        type: secret
        name: continuwuity-secrets
        defaultMode: 0400
        advancedMounts:
          app:
            app:
              - subPath: CONDUWUIT_LDAP__BIND_PASSWORD # continuwuity doesn't allow env var for this
                path: *ldap-secret
                readOnly: true
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostAliases:
        - ip: "${APP_IP_AUTHENTIK:=127.0.0.1}"
          hostnames: ["${APP_DNS_AUTHENTIK:=authentik}"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      # hostUsers: false
      runtimeClassName: kata
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 65534
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: Always
        seccompProfile: { type: "RuntimeDefault" }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "fuckoff.home.arpa/{{ .Release.Name }}"
                    operator: DoesNotExist
    networkpolicies:
      app:
        controller: app
        policyTypes: [Ingress, Egress]
        rules:
          ingress:
            - from:
                - &netpol-uwu
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: out-of-your-element
                  namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: out-of-your-element
          egress:
            - to: [*netpol-uwu]
