---
# this Kustomization is only for bootstrapping with `kustomize build --enable-helm`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.17.3
    releaseName: cilium
    namespace: kube-system
    valuesFile: helm-values.yaml
commonAnnotations:
  meta.helm.sh/release-name: cilium
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
