---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-app
  namespace: &ns trust-manager
  labels: &l
    app.kubernetes.io/name: "trust-manager"
    substitution.flux.home.arpa/disabled: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/tls/trust-manager/app
  components:
    - ../../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: 1-core-tls-cert-manager-app
      namespace: flux-system
