---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: searxng-config
    namespace: searxng
    files:
      - settings.yml
generatorOptions:
  disableNameSuffixHash: true
